# Generated by Django 5.0.6 on 2026-09-20 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the draw month', unique=True)),
                ('winning_numbers', models.JSONField(help_text='List of 5 unique numbers, 1-45')),
                ('method', models.CharField(choices=[('random', 'Random'), ('weighted', 'Weighted by score frequency')], default='random', max_length=10)),
                ('published', models.BooleanField(default=False)),
                ('prize_pool_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jackpot_rollover_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('5', '5-Number match'), ('4', '4-Number match'), ('3', '3-Number match')], max_length=1)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='winner_proofs/')),
                ('verified', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='draws.drawresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
